from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Text, JSON
from sqlalchemy.sql import func
from app.db.base_class import Base

class CorrectionLog(Base):
    __tablename__ = "correction_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    org_id = Column(Integer, ForeignKey("organizations.id"), nullable=False, index=True)
    post_id = Column(Integer, ForeignKey("post.id"), nullable=False, index=True)
    
    # Store the exact version generated by the AI
    original_ai_draft = Column(Text, nullable=False)
    
    # Store the final version after the user edited it
    human_edited_draft = Column(Text, nullable=False)
    
    # Optional: The output of a diffing algorithm (diff-match-patch) for easy access
    computed_diff = Column(JSON, nullable=True)
    
    # Used to categorize the edit (e.g. Tone, Formatting, Accuracy)
    edit_category = Column(String, nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Used to denote if this pair has already been sent to a fine-tuning dataset
    processed_for_tuning = Column(Integer, default=0)
