"""Add modular models and pgvector

Revision ID: 2683c8582bdc
Revises: 
Create Date: 2026-02-26 02:23:22.385272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2683c8582bdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetunedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_role', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('completion', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finetunedata_agent_role'), 'finetunedata', ['agent_role'], unique=False)
    op.create_index(op.f('ix_finetunedata_id'), 'finetunedata', ['id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('tracked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_id'), 'performance_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_post_id'), 'performance_metrics', ['post_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('title', sa.JSON(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('conclusion', sa.JSON(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('subcategory', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('survey', sa.JSON(), nullable=True),
    sa.Column('image_prompt', sa.JSON(), nullable=True),
    sa.Column('image_data', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.JSON(), nullable=True),
    sa.Column('image_crm', sa.JSON(), nullable=True),
    sa.Column('all_image_data', sa.JSON(), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('seo_data', sa.JSON(), nullable=True),
    sa.Column('research_sources', sa.JSON(), nullable=True),
    sa.Column('pub_platform', sa.String(), nullable=True),
    sa.Column('pub_meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('refresh_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tasks_id'), 'refresh_tasks', ['id'], unique=False)
    op.create_table('scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trending_id', sa.String(), nullable=True),
    sa.Column('url', sa.JSON(), nullable=True),
    sa.Column('title', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('short_content', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_id'), 'scrape', ['id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=511), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    op.create_table('task_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('preview_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_id'), 'task_progress', ['id'], unique=False)
    op.create_index(op.f('ix_task_progress_task_id'), 'task_progress', ['task_id'], unique=True)
    op.create_table('trending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('related_topics_rising', sa.JSON(), nullable=True),
    sa.Column('related_topics_top', sa.JSON(), nullable=True),
    sa.Column('related_query_rising', sa.JSON(), nullable=True),
    sa.Column('related_query_top', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.Column('trend_score', sa.Integer(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Integer(), nullable=True),
    sa.Column('social_mentions', sa.Integer(), nullable=True),
    sa.Column('competition_gap', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_id'), 'trending', ['id'], unique=False)
    op.create_table('trustsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trustsource_domain'), 'trustsource', ['domain'], unique=True)
    op.create_index(op.f('ix_trustsource_id'), 'trustsource', ['id'], unique=False)
    op.create_table('twitterpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitterpost_id'), 'twitterpost', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=511), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_table('content_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('primary_intent', sa.String(length=100), nullable=True),
    sa.Column('secondary_intents', sa.JSON(), nullable=True),
    sa.Column('core_topics', sa.JSON(), nullable=True),
    sa.Column('word_count_target', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_id'), 'content_briefs', ['id'], unique=False)
    op.create_table('serp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('search_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_snapshots_id'), 'serp_snapshots', ['id'], unique=False)
    op.create_table('outlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlines_id'), 'outlines', ['id'], unique=False)
    op.create_table('serp_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('salience', sa.Float(), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['serp_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_entities_entity_name'), 'serp_entities', ['entity_name'], unique=False)
    op.create_index(op.f('ix_serp_entities_id'), 'serp_entities', ['id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    op.create_table('seo_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('title_tag', sa.String(length=255), nullable=True),
    sa.Column('meta_desc', sa.String(length=511), nullable=True),
    sa.Column('focus_keyword', sa.String(length=255), nullable=True),
    sa.Column('primary_slug', sa.String(length=255), nullable=True),
    sa.Column('schema_markup', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_metadata_id'), 'seo_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_seo_metadata_primary_slug'), 'seo_metadata', ['primary_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_metadata_primary_slug'), table_name='seo_metadata')
    op.drop_index(op.f('ix_seo_metadata_id'), table_name='seo_metadata')
    op.drop_table('seo_metadata')
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_serp_entities_id'), table_name='serp_entities')
    op.drop_index(op.f('ix_serp_entities_entity_name'), table_name='serp_entities')
    op.drop_table('serp_entities')
    op.drop_index(op.f('ix_outlines_id'), table_name='outlines')
    op.drop_table('outlines')
    op.drop_index(op.f('ix_serp_snapshots_id'), table_name='serp_snapshots')
    op.drop_table('serp_snapshots')
    op.drop_index(op.f('ix_content_briefs_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_twitterpost_id'), table_name='twitterpost')
    op.drop_table('twitterpost')
    op.drop_index(op.f('ix_trustsource_id'), table_name='trustsource')
    op.drop_index(op.f('ix_trustsource_domain'), table_name='trustsource')
    op.drop_table('trustsource')
    op.drop_index(op.f('ix_trending_id'), table_name='trending')
    op.drop_table('trending')
    op.drop_index(op.f('ix_task_progress_task_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_id'), table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_scrape_id'), table_name='scrape')
    op.drop_table('scrape')
    op.drop_index(op.f('ix_refresh_tasks_id'), table_name='refresh_tasks')
    op.drop_table('refresh_tasks')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_performance_metrics_post_id'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_finetunedata_id'), table_name='finetunedata')
    op.drop_index(op.f('ix_finetunedata_agent_role'), table_name='finetunedata')
    op.drop_table('finetunedata')
    # ### end Alembic commands ###
