"""add telemetry and seo fields to post

Revision ID: 705940bb5411
Revises: 2683c8582bdc
Create Date: 2026-03-02 19:54:48.827729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705940bb5411'
down_revision: Union[str, Sequence[str], None] = '2683c8582bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('agent_telemetry', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'agent_telemetry')
    # ### end Alembic commands ###
