"""initial production schema

Revision ID: de1d66f07129
Revises: 
Create Date: 2026-05-03 15:01:29.172408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'de1d66f07129'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetunedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_role', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('completion', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finetunedata_agent_role'), 'finetunedata', ['agent_role'], unique=False)
    op.create_index(op.f('ix_finetunedata_id'), 'finetunedata', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('brand_voice', sa.String(), nullable=True),
    sa.Column('brand_tone', sa.String(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('products_services', sa.String(), nullable=True),
    sa.Column('usp', sa.String(), nullable=True),
    sa.Column('content_goals', sa.String(), nullable=True),
    sa.Column('preferred_keywords', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('key_messages', sa.String(), nullable=True),
    sa.Column('competitors', sa.String(), nullable=True),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('trustsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trustsource_domain'), 'trustsource', ['domain'], unique=True)
    op.create_index(op.f('ix_trustsource_id'), 'trustsource', ['id'], unique=False)
    op.create_table('twitterpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitterpost_id'), 'twitterpost', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('role_position', sa.String(), nullable=True),
    sa.Column('writing_preference', sa.String(), nullable=True),
    sa.Column('audience_familiarity', sa.String(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_id'), 'credit_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_org_id'), 'credit_ledger', ['org_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('title', sa.JSON(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('conclusion', sa.JSON(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('subcategory', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('survey', sa.JSON(), nullable=True),
    sa.Column('image_prompt', sa.JSON(), nullable=True),
    sa.Column('image_data', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.JSON(), nullable=True),
    sa.Column('image_crm', sa.JSON(), nullable=True),
    sa.Column('all_image_data', sa.JSON(), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('seo_data', sa.JSON(), nullable=True),
    sa.Column('research_sources', sa.JSON(), nullable=True),
    sa.Column('agent_telemetry', sa.JSON(), nullable=True),
    sa.Column('pub_platform', sa.String(), nullable=True),
    sa.Column('pub_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_index(op.f('ix_post_org_id'), 'post', ['org_id'], unique=False)
    op.create_table('scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('trending_id', sa.String(), nullable=True),
    sa.Column('url', sa.JSON(), nullable=True),
    sa.Column('title', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('short_content', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_id'), 'scrape', ['id'], unique=False)
    op.create_index(op.f('ix_scrape_org_id'), 'scrape', ['org_id'], unique=False)
    op.create_table('task_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('preview_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_id'), 'task_progress', ['id'], unique=False)
    op.create_index(op.f('ix_task_progress_org_id'), 'task_progress', ['org_id'], unique=False)
    op.create_index(op.f('ix_task_progress_status'), 'task_progress', ['status'], unique=False)
    op.create_index(op.f('ix_task_progress_task_id'), 'task_progress', ['task_id'], unique=True)
    op.create_table('trending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('related_topics_rising', sa.JSON(), nullable=True),
    sa.Column('related_topics_top', sa.JSON(), nullable=True),
    sa.Column('related_query_rising', sa.JSON(), nullable=True),
    sa.Column('related_query_top', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rep_count', sa.String(), nullable=True),
    sa.Column('trend_score', sa.Integer(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Integer(), nullable=True),
    sa.Column('social_mentions', sa.Integer(), nullable=True),
    sa.Column('competition_gap', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_id'), 'trending', ['id'], unique=False)
    op.create_index(op.f('ix_trending_org_id'), 'trending', ['org_id'], unique=False)
    op.create_table('user_organization',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_table('workspace_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_assets_id'), 'workspace_assets', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_assets_org_id'), 'workspace_assets', ['org_id'], unique=False)
    op.create_table('asset_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('chunk_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['workspace_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_embedding_hnsw', 'asset_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_asset_embeddings_asset_id'), 'asset_embeddings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_embeddings_id'), 'asset_embeddings', ['id'], unique=False)
    op.create_table('correction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('original_ai_draft', sa.Text(), nullable=False),
    sa.Column('human_edited_draft', sa.Text(), nullable=False),
    sa.Column('computed_diff', sa.JSON(), nullable=True),
    sa.Column('edit_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_for_tuning', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_logs_id'), 'correction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_correction_logs_org_id'), 'correction_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_correction_logs_post_id'), 'correction_logs', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_logs_post_id'), table_name='correction_logs')
    op.drop_index(op.f('ix_correction_logs_org_id'), table_name='correction_logs')
    op.drop_index(op.f('ix_correction_logs_id'), table_name='correction_logs')
    op.drop_table('correction_logs')
    op.drop_index(op.f('ix_asset_embeddings_id'), table_name='asset_embeddings')
    op.drop_index(op.f('ix_asset_embeddings_asset_id'), table_name='asset_embeddings')
    op.drop_index('idx_asset_embedding_hnsw', table_name='asset_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('asset_embeddings')
    op.drop_index(op.f('ix_workspace_assets_org_id'), table_name='workspace_assets')
    op.drop_index(op.f('ix_workspace_assets_id'), table_name='workspace_assets')
    op.drop_table('workspace_assets')
    op.drop_table('user_organization')
    op.drop_index(op.f('ix_trending_org_id'), table_name='trending')
    op.drop_index(op.f('ix_trending_id'), table_name='trending')
    op.drop_table('trending')
    op.drop_index(op.f('ix_task_progress_task_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_status'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_org_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_id'), table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_index(op.f('ix_scrape_org_id'), table_name='scrape')
    op.drop_index(op.f('ix_scrape_id'), table_name='scrape')
    op.drop_table('scrape')
    op.drop_index(op.f('ix_post_org_id'), table_name='post')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_credit_ledger_org_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_twitterpost_id'), table_name='twitterpost')
    op.drop_table('twitterpost')
    op.drop_index(op.f('ix_trustsource_id'), table_name='trustsource')
    op.drop_index(op.f('ix_trustsource_domain'), table_name='trustsource')
    op.drop_table('trustsource')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_finetunedata_id'), table_name='finetunedata')
    op.drop_index(op.f('ix_finetunedata_agent_role'), table_name='finetunedata')
    op.drop_table('finetunedata')
    # ### end Alembic commands ###
